package com.nyaai.ui.strings

import com.nyaai.ui.state.AppLanguage

// ── String resource data class ───────────────────────────────────────────────
data class AppStrings(
    // Chat screen
    val whatCanIHelpWith: String,
    val scanDocument: String,
    val knowYourFIR: String,
    val draftRentAgreement: String,
    val consumerRightsOverview: String,
    val chatInputHint: String,
    // Welcome
    val welcomeTo: String,
    val tagline: String,
    // Bottom nav
    val navChat: String,
    val navAbout: String,
    val navSettings: String,
    // Drawer
    val chatHistory: String,
    val bookmarksTitle: String = "Saved Bookmarks",
    val noBookmarksYet: String = "No saved bookmarks yet",
    val bookmarkedToast: String = "Saved to Bookmarks",
    val removedBookmarkToast: String = "Removed from Bookmarks",
    val scanningDocument: String = "Scanning document...",
    // Settings
    val settingsTitle: String,
    val sectionAppearance: String,
    val theme: String,
    val themeLight: String,
    val themeSystem: String,
    val themeDark: String,
    val sectionPreferences: String,
    val notifications: String,
    val notificationsSubtitle: String,
    val appLanguage: String,
    val lowBandwidthMode: String,
    val lowBandwidthSubtitle: String,
    val aiResponseLanguage: String,
    val aiResponseLangValue: String,
    val sectionPrivacy: String,
    val clearChatHistory: String,
    val clearChatSubtitle: String,
    val privacyPolicy: String,
    val logOut: String,
    val logOutSubtitle: String,
    val langModalTitle: String,
    // Privacy Policy Dialog
    val disclaimerTitle: String,
    val disclaimerBody: String,
    val disclaimerBullet1: String,
    val disclaimerBullet2: String,
    val disclaimerBullet3: String,
    val iUnderstand: String,
    // About
    val aboutTitle: String,
    val aboutSubtitle: String,
    val visionTitle: String,
    val visionPara1: String,
    val visionPara2: String,
    val visionPara3: String,
    val visionPara4: String,
    val madeWithCare: String = "Made with care for India.",
    // Legal SOS
    val legalSosTitle: String,
    // Workspace / Matters
    val myMattersTitle: String = "My Cases",
    val searchMattersHint: String = "Search cases, domains, states...",
    val whatHappenedAction: String = "What happened?",
    val startCaseIntake: String = "Start Case Intake",
    val noMattersYet: String = "No cases yet",
    val noMattersDesc: String = "Describe what happened to get an actionable legal roadmap.",
    val syncedBadge: String = "Synced",
    val deleteMatterAction: String = "Delete Case",
    val tabOverview: String = "Overview",
    val tabTimeline: String = "Timeline",
    val tabActionPlan: String = "Action Plan",
    val tabEvidence: String = "Evidence",
    val tabCitations: String = "Citations",
    val tabQuestions: String = "Questions",
    // Verification Badges
    val badgeSeniorAdvocate: String = "⚖️ Senior Advocate Procedural Framework",
    val badgeVerifiedIndianLaw: String = "🏛️ Grounded in Verified Indian Law",
    val badgeCodifiedExcerpts: String = "📖 Codified Statutory Excerpts",
    val badgeVerifiedStatutes: String = "✓ Grounded in Verified Statutes",
    val badgeStatutoryGuide: String = "⚡ Statutory Reference Guide",
    val badgePreliminaryGuidance: String = "ℹ️ Preliminary Legal Guidance",
)

// ── English ───────────────────────────────────────────────────────────────────
val englishStrings = AppStrings(
    whatCanIHelpWith      = "What can I help with?",
    scanDocument          = "Scan Document",
    knowYourFIR           = "Know Your FIR",
    draftRentAgreement    = "Draft a rent agreement",
    consumerRightsOverview = "Consumer rights overview",
    chatInputHint         = "What can i help with?",
    welcomeTo             = "Welcome to",
    tagline               = "Know your rights",
    navChat               = "Chat",
    navAbout              = "About",
    navSettings           = "Settings",
    chatHistory           = "Chat History",
    settingsTitle         = "Settings",
    sectionAppearance     = "APPEARANCE",
    theme                 = "Theme",
    themeLight            = "☀ Light",
    themeSystem           = "✓ System",
    themeDark             = "🌙 Dark",
    sectionPreferences    = "PREFERENCES",
    notifications         = "Notifications",
    notificationsSubtitle = "Manage alerts and updates",
    appLanguage           = "App Language",
    lowBandwidthMode      = "Low Bandwidth Mode",
    lowBandwidthSubtitle  = "Compresses AI answers to save data over 2G/slow networks.",
    aiResponseLanguage    = "AI Response Language",
    aiResponseLangValue   = "Hinglish (Gen-Z)",
    sectionPrivacy        = "PRIVACY & DATA",
    clearChatHistory      = "Clear Chat History",
    clearChatSubtitle     = "Delete all conversations from this device",
    privacyPolicy         = "Privacy Policy",
    logOut                = "Log Out",
    logOutSubtitle        = "Sign out of your account",
    langModalTitle        = "App Language",
    disclaimerTitle       = "Disclaimer",
    disclaimerBody        = "Nyaai provides AI-generated legal information for educational purposes only.",
    disclaimerBullet1     = "• This app is not a substitute for professional legal advice.",
    disclaimerBullet2     = "• The information provided may not be complete or up-to-date.",
    disclaimerBullet3     = "• Always consult a qualified lawyer for serious legal matters.",
    iUnderstand           = "I Understand",
    aboutTitle            = "About",
    aboutSubtitle         = "Discover the story behind the app.",
    visionTitle           = "The Vision Behind Nyaai",
    visionPara1           = "In India, countless citizens remain unaware of their fundamental rights because laws are often heavily codified, and legal counsel can be prohibitively expensive or inaccessible.",
    visionPara2           = "Nyaai was designed to bridge this critical gap by democratizing legal knowledge. By leveraging AI to translate complex statutes into simple, everyday language, Nyaai empowers individuals to understand their rights and make informed decisions.",
    visionPara3           = "We strive to support everyone—especially those in rural or underserved communities—by putting the power of legal awareness directly into the hands of the people.",
    visionPara4           = "Justice begins with knowledge, and Nyaai is here to ensure that knowledge is available to all.",
    madeWithCare          = "Made with care for India.",
    legalSosTitle         = "Legal SOS & Helplines",
    myMattersTitle        = "My Cases",
    searchMattersHint     = "Search cases, domains, states...",
    whatHappenedAction    = "What happened?",
    startCaseIntake       = "Start Case Intake",
    noMattersYet          = "No cases yet",
    noMattersDesc         = "Describe what happened to get an actionable legal roadmap.",
    syncedBadge           = "Synced",
    deleteMatterAction    = "Delete Case",
    tabOverview           = "Overview",
    tabTimeline           = "Timeline",
    tabActionPlan         = "Action Plan",
    tabEvidence           = "Evidence",
    tabCitations          = "Citations",
    tabQuestions          = "Questions",
    badgeSeniorAdvocate   = "⚖️ Senior Advocate Procedural Framework",
    badgeVerifiedIndianLaw = "🏛️ Grounded in Verified Indian Law",
    badgeCodifiedExcerpts = "📖 Codified Statutory Excerpts",
    badgeVerifiedStatutes = "✓ Grounded in Verified Statutes",
    badgeStatutoryGuide   = "⚡ Statutory Reference Guide",
    badgePreliminaryGuidance = "ℹ️ Preliminary Legal Guidance",
)

// ── Hindi (हिंदी) ─────────────────────────────────────────────────────────────
val hindiStrings = AppStrings(
    whatCanIHelpWith      = "मैं आपकी क्या सहायता कर सकता हूं?",
    scanDocument          = "दस्तावेज़ स्कैन करें",
    knowYourFIR           = "अपनी FIR जानें",
    draftRentAgreement    = "किराया समझौता बनाएं",
    consumerRightsOverview = "उपभोक्ता अधिकारों का अवलोकन",
    chatInputHint         = "मैं आपकी क्या सहायता कर सकता हूं?",
    welcomeTo             = "स्वागत है",
    tagline               = "अपने अधिकार जानें",
    navChat               = "चैट",
    navAbout              = "जानकारी",
    navSettings           = "सेटिंग्स",
    chatHistory           = "चैट इतिहास",
    settingsTitle         = "सेटिंग्स",
    sectionAppearance     = "दिखावट",
    theme                 = "थीम",
    themeLight            = "☀ हल्का",
    themeSystem           = "✓ सिस्टम",
    themeDark             = "🌙 गहरा",
    sectionPreferences    = "प्राथमिकताएं",
    notifications         = "सूचनाएं",
    notificationsSubtitle = "अलर्ट और अपडेट प्रबंधित करें",
    appLanguage           = "ऐप भाषा",
    lowBandwidthMode      = "कम बैंडविड्थ मोड",
    lowBandwidthSubtitle  = "2G/धीमे नेटवर्क पर डेटा बचाने के लिए AI उत्तर संपीड़ित करता है।",
    aiResponseLanguage    = "AI प्रतिक्रिया भाषा",
    aiResponseLangValue   = "हिंग्लिश (Gen-Z)",
    sectionPrivacy        = "गोपनीयता और डेटा",
    clearChatHistory      = "चैट इतिहास साफ़ करें",
    clearChatSubtitle     = "इस डिवाइस से सभी बातचीत हटाएं",
    privacyPolicy         = "गोपनीयता नीति",
    logOut                = "लॉग आउट",
    logOutSubtitle        = "अपने खाते से साइन आउट करें",
    langModalTitle        = "ऐप भाषा",
    disclaimerTitle       = "अस्वीकरण",
    disclaimerBody        = "न्याई केवल शैक्षिक उद्देश्यों के लिए AI-जनित कानूनी जानकारी प्रदान करता है।",
    disclaimerBullet1     = "• यह ऐप पेशेवर कानूनी सलाह का विकल्प नहीं है।",
    disclaimerBullet2     = "• दी गई जानकारी पूर्ण या अद्यतन नहीं हो सकती।",
    disclaimerBullet3     = "• गंभीर कानूनी मामलों के लिए किसी योग्य वकील से परामर्श करें।",
    iUnderstand           = "मैं समझ गया",
    aboutTitle            = "जानकारी",
    aboutSubtitle         = "ऐप के पीछे की कहानी जानें।",
    visionTitle           = "न्याई की दृष्टि",
    visionPara1           = "भारत में, अनगिनत नागरिक अपने मौलिक अधिकारों से अनजान रहते हैं क्योंकि कानून अक्सर जटिल होते हैं, और कानूनी सलाह महंगी या अनुपलब्ध हो सकती है।",
    visionPara2           = "न्याई को कानूनी ज्ञान को लोकतांत्रिक बनाकर इस महत्वपूर्ण अंतर को पाटने के लिए डिज़ाइन किया गया था। AI का उपयोग करके जटिल कानूनों को सरल, रोजमर्रा की भाषा में अनुवाद करके, न्याई व्यक्तियों को अपने अधिकारों को समझने और सूचित निर्णय लेने में सक्षम बनाता है।",
    visionPara3           = "हम सभी को समर्थन देने का प्रयास करते हैं—विशेष रूप से ग्रामीण या वंचित समुदायों में—कानूनी जागरूकता की शक्ति को सीधे लोगों के हाथों में देकर।",
    visionPara4           = "न्याय ज्ञान से शुरू होता है, और न्याई यहाँ यह सुनिश्चित करने के लिए है कि यह ज्ञान सभी के लिए उपलब्ध हो।",
    bookmarksTitle        = "सहेजे गए बुकमार्क",
    noBookmarksYet        = "अभी तक कोई सहेजा गया बुकमार्क नहीं है",
    bookmarkedToast       = "बुकमार्क में सहेजा गया",
    removedBookmarkToast  = "बुकमार्क से हटाया गया",
    scanningDocument      = "दस्तावेज़ स्कैन किया जा रहा है...",
    madeWithCare          = "भारत के लिए प्यार से बनाया गया।",
    legalSosTitle         = "कानूनी SOS और हेल्पलाइन",
    myMattersTitle        = "मेरे मामले",
    searchMattersHint     = "मामले, क्षेत्र, राज्य खोजें...",
    whatHappenedAction    = "क्या हुआ?",
    startCaseIntake       = "केस का विवरण दर्ज करें",
    noMattersYet          = "अभी तक कोई मामला नहीं",
    noMattersDesc         = "कार्यवाही योग्य कानूनी रोडमैप पाने के लिए बताएं कि क्या हुआ।",
    syncedBadge           = "सिंक किया गया",
    deleteMatterAction    = "मामला हटाएं",
    tabOverview           = "अवलोकन",
    tabTimeline           = "समयरेखा",
    tabActionPlan         = "कार्य योजना",
    tabEvidence           = "साक्ष्य एवं प्रमाण",
    tabCitations          = "कानूनी धाराएं",
    tabQuestions          = "महत्वपूर्ण प्रश्न",
    badgeSeniorAdvocate   = "⚖️ वरिष्ठ अधिवक्ता प्रक्रियात्मक ढांचा",
    badgeVerifiedIndianLaw = "🏛️ सत्यापित भारतीय कानून पर आधारित",
    badgeCodifiedExcerpts = "📖 संहिताबद्ध वैधानिक अंश",
    badgeVerifiedStatutes = "✓ सत्यापित संहिताओं पर आधारित",
    badgeStatutoryGuide   = "⚡ वैधानिक संदर्भ निर्देशिका",
    badgePreliminaryGuidance = "ℹ️ प्रारंभिक कानूनी मार्गदर्शन",
)

// ── Bengali (বাংলা) ───────────────────────────────────────────────────────────
val bengaliStrings = AppStrings(
    whatCanIHelpWith      = "আমি কীভাবে সাহায্য করতে পারি?",
    scanDocument          = "নথি স্ক্যান করুন",
    knowYourFIR           = "আপনার FIR জানুন",
    draftRentAgreement    = "ভাড়া চুক্তি তৈরি করুন",
    consumerRightsOverview = "ভোক্তা অধিকারের সংক্ষিপ্ত বিবরণ",
    chatInputHint         = "আমি কীভাবে সাহায্য করতে পারি?",
    welcomeTo             = "স্বাগতম",
    tagline               = "আপনার অধিকার জানুন",
    navChat               = "চ্যাট",
    navAbout              = "সম্পর্কে",
    navSettings           = "সেটিংস",
    chatHistory           = "চ্যাট ইতিহাস",
    settingsTitle         = "সেটিংস",
    sectionAppearance     = "চেহারা",
    theme                 = "থিম",
    themeLight            = "☀ হালকা",
    themeSystem           = "✓ সিস্টেম",
    themeDark             = "🌙 গাঢ়",
    sectionPreferences    = "পছন্দ",
    notifications         = "বিজ্ঞপ্তি",
    notificationsSubtitle = "সতর্কতা এবং আপডেট পরিচালনা করুন",
    appLanguage           = "অ্যাপ ভাষা",
    lowBandwidthMode      = "কম ব্যান্ডউইথ মোড",
    lowBandwidthSubtitle  = "2G/ধীর নেটওয়ার্কে ডেটা সাশ্রয় করতে AI উত্তর সংকুচিত করে।",
    aiResponseLanguage    = "AI প্রতিক্রিয়া ভাষা",
    aiResponseLangValue   = "হিংলিশ (Gen-Z)",
    sectionPrivacy        = "গোপনীয়তা ও ডেটা",
    clearChatHistory      = "চ্যাট ইতিহাস মুছুন",
    clearChatSubtitle     = "এই ডিভাইস থেকে সমস্ত কথোপকথন মুছুন",
    privacyPolicy         = "গোপনীয়তা নীতি",
    logOut                = "লগ আউট",
    logOutSubtitle        = "আপনার অ্যাকাউন্ট থেকে সাইন আউট করুন",
    langModalTitle        = "অ্যাপ ভাষা",
    disclaimerTitle       = "দাবিত্যাগ",
    disclaimerBody        = "ন্যায়াই শুধুমাত্র শিক্ষামূলক উদ্দেশ্যে AI-উৎপাদিত আইনি তথ্য প্রদান করে।",
    disclaimerBullet1     = "• এই অ্যাপ পেশাদার আইনি পরামর্শের বিকল্প নয়।",
    disclaimerBullet2     = "• প্রদত্ত তথ্য সম্পূর্ণ বা আপ-টু-ডেট নাও হতে পারে।",
    disclaimerBullet3     = "• গুরুতর আইনি বিষয়ে সর্বদা একজন যোগ্য আইনজীবীর পরামর্শ নিন।",
    iUnderstand           = "আমি বুঝেছি",
    aboutTitle            = "সম্পর্কে",
    aboutSubtitle         = "অ্যাপের পেছনের গল্প আবিষ্কার করুন।",
    visionTitle           = "ন্যায়ের দৃষ্টিভঙ্গি",
    visionPara1           = "ভারতে, অসংখ্য নাগরিক তাদের মৌলিক অধিকার সম্পর্কে অজ্ঞ থাকেন কারণ আইনগুলি প্রায়শই জটিলভাবে সংহিতাবদ্ধ, এবং আইনি পরামর্শ ব্যয়বহুল বা অপ্রাপ্য হতে পারে।",
    visionPara2           = "আইনি জ্ঞানকে গণতান্ত্রিক করে এই গুরুত্বপূর্ণ ব্যবধান পূরণ করতে ন্যায়াই ডিজাইন করা হয়েছিল। AI ব্যবহার করে জটিল আইনগুলিকে সহজ, দৈনন্দিন ভাষায় অনুবাদ করে, ন্যায়াই ব্যক্তিদের তাদের অধিকার বুঝতে এবং সচেতন সিদ্ধান্ত নিতে সক্ষম করে।",
    visionPara3           = "আমরা সবাইকে সমর্থন করার চেষ্টা করি—বিশেষত গ্রামীণ বা সুবিধাবঞ্চিত সম্প্রদায়গুলিতে—সরাসরি মানুষের হাতে আইনি সচেতনতার শক্তি দিয়ে।",
    visionPara4           = "ন্যায়বিচার জ্ঞান দিয়ে শুরু হয়, এবং ন্যায়াই এখানে নিশ্চিত করতে এসেছে যে সেই জ্ঞান সবার জন্য উপলব্ধ।",
    bookmarksTitle        = "সংরক্ষিত বুকমার্ক",
    noBookmarksYet        = "এখনও কোনও সংরক্ষিত বুকমার্ক নেই",
    bookmarkedToast       = "বুকমার্কে সংরক্ষণ করা হয়েছে",
    removedBookmarkToast  = "বুকমার্ক থেকে সরানো হয়েছে",
    scanningDocument      = "নথি স্ক্যান করা হচ্ছে...",
    madeWithCare          = "ভারতের জন্য যত্ন সহকারে তৈরি।",
    legalSosTitle         = "আইনি SOS ও হেল্পলাইন",
    myMattersTitle        = "আমার মামলাসমূহ",
    searchMattersHint     = "মামলা, ক্ষেত্র, রাজ্য খুঁজুন...",
    whatHappenedAction    = "কী ঘটেছে?",
    startCaseIntake       = "মামলার বিবরণ শুরু করুন",
    noMattersYet          = "এখনও কোনও মামলা নেই",
    noMattersDesc         = "কার্যকর আইনি রূপরেখা পেতে কী ঘটেছে তা বর্ণনা করুন।",
    syncedBadge           = "সিঙ্ক করা হয়েছে",
    deleteMatterAction    = "মামলা মুছুন",
    tabOverview           = "সংক্ষিপ্ত বিবরণ",
    tabTimeline           = "সময়রেখা",
    tabActionPlan         = "কর্ম পরিকল্পনা",
    tabEvidence           = "প্রমাণাদি",
    tabCitations          = "আইনি ধারা",
    tabQuestions          = "জরুরি প্রশ্নাবলী",
    badgeSeniorAdvocate   = "⚖️ সিনিয়র অ্যাডভোকেট পদ্ধতিগত কাঠামো",
    badgeVerifiedIndianLaw = "🏛️ যাচাইকৃত ভারতীয় আইনের ভিত্তিতে গঠিত",
    badgeCodifiedExcerpts = "📖 বিধিবদ্ধ আইনের উদ্ধৃতি",
    badgeVerifiedStatutes = "✓ যাচাইকৃত বিধিমালার ভিত্তিতে",
    badgeStatutoryGuide   = "⚡ বিধিবদ্ধ রেফারেন্স নির্দেশিকা",
    badgePreliminaryGuidance = "ℹ️ প্রাথমিক আইনি দিকনির্দেশনা",
)

// ── Telugu (తెలుగు) ───────────────────────────────────────────────────────────
val teluguStrings = AppStrings(
    whatCanIHelpWith      = "నేను ఎలా సహాయపడగలను?",
    scanDocument          = "పత్రాన్ని స్కాన్ చేయండి",
    knowYourFIR           = "మీ FIR తెలుసుకోండి",
    draftRentAgreement    = "అద్దె ఒప్పందం రూపొందించండి",
    consumerRightsOverview = "వినియోగదారు హక్కుల అవలోకనం",
    chatInputHint         = "నేను ఎలా సహాయపడగలను?",
    welcomeTo             = "స్వాగతం",
    tagline               = "మీ హక్కులు తెలుసుకోండి",
    navChat               = "చాట్",
    navAbout              = "గురించి",
    navSettings           = "సెట్టింగ్‌లు",
    chatHistory           = "చాట్ చరిత్ర",
    settingsTitle         = "సెట్టింగ్‌లు",
    sectionAppearance     = "రూప రేఖ",
    theme                 = "థీమ్",
    themeLight            = "☀ వెలుతురు",
    themeSystem           = "✓ సిస్టమ్",
    themeDark             = "🌙 చీకటి",
    sectionPreferences    = "ప్రాధాన్యతలు",
    notifications         = "నోటిఫికేషన్లు",
    notificationsSubtitle = "హెచ్చరికలు మరియు నవీకరణలు నిర్వహించండి",
    appLanguage           = "యాప్ భాష",
    lowBandwidthMode      = "తక్కువ బ్యాండ్‌విడ్త్ మోడ్",
    lowBandwidthSubtitle  = "2G/నెమ్మది నెట్‌వర్క్‌లో డేటా ఆదా చేయడానికి AI సమాధానాలను కంప్రెస్ చేస్తుంది.",
    aiResponseLanguage    = "AI ప్రతిస్పందన భాష",
    aiResponseLangValue   = "హింగ్లిష్ (Gen-Z)",
    sectionPrivacy        = "గోప్యత మరియు డేటా",
    clearChatHistory      = "చాట్ చరిత్రను క్లియర్ చేయండి",
    clearChatSubtitle     = "ఈ పరికరం నుండి అన్ని సంభాషణలను తొలగించండి",
    privacyPolicy         = "గోప్యతా విధానం",
    logOut                = "లాగ్ అవుట్",
    logOutSubtitle        = "మీ ఖాతా నుండి సైన్ అవుట్ అవ్వండి",
    langModalTitle        = "యాప్ భాష",
    disclaimerTitle       = "నిరాకరణ",
    disclaimerBody        = "న్యాయి కేవలం విద్యా ప్రయోజనాల కోసం AI-రూపొందించిన చట్టపరమైన సమాచారాన్ని అందిస్తుంది.",
    disclaimerBullet1     = "• ఈ యాప్ వృత్తిపరమైన చట్టపరమైన సలహాకు ప్రత్యామ్నాయం కాదు.",
    disclaimerBullet2     = "• అందించిన సమాచారం పూర్తిగా లేదా తాజాగా ఉండకపోవచ్చు.",
    disclaimerBullet3     = "• తీవ్రమైన చట్టపరమైన విషయాలకు అర్హులైన న్యాయవాదిని సంప్రదించండి.",
    iUnderstand           = "నాకు అర్థమైంది",
    aboutTitle            = "గురించి",
    aboutSubtitle         = "యాప్ వెనుక కథను కనుగొనండి.",
    visionTitle           = "న్యాయి వెనుక దృష్టి",
    visionPara1           = "భారతదేశంలో, చట్టాలు తరచుగా క్లిష్టంగా ఉన్నందున మరియు న్యాయ సలహా అందుబాటులో లేకపోవడం వల్ల అసంఖ్యాక పౌరులు తమ ప్రాథమిక హక్కుల గురించి తెలియకుండా ఉంటారు.",
    visionPara2           = "న్యాయ జ్ఞానాన్ని ప్రజాస్వామ్యీకరించడం ద్వారా ఈ కీలకమైన అంతరాన్ని పూరించడానికి న్యాయి రూపొందించబడింది. AI ఉపయోగించి సంక్లిష్ట చట్టాలను సరళమైన రోజువారీ భాషలోకి అనువదించడం ద్వారా, న్యాయి వ్యక్తులు తమ హక్కులను అర్థం చేసుకుని సమాచారోపేత నిర్ణయాలు తీసుకోవడానికి వీలు కల్పిస్తుంది.",
    visionPara3           = "మేము అందరికీ మద్దతు ఇవ్వడానికి ప్రయత్నిస్తాం—ముఖ్యంగా గ్రామీణ లేదా వెనుకబడిన సమాజాలలో వారికి—చట్టపరమైన అవగాహన శక్తిని నేరుగా ప్రజల చేతుల్లోకి తీసుకురావడం ద్వారా.",
    visionPara4           = "న్యాయం జ్ఞానంతో మొదలవుతుంది, మరియు న్యాయి ఆ జ్ఞానం అందరికీ అందుబాటులో ఉండేలా చేయడానికి ఇక్కడ ఉంది.",
    bookmarksTitle        = "భద్రపరచిన బుక్‌మార్క్‌లు",
    noBookmarksYet        = "ఇంకా ఎలాంటి బుక్‌మార్క్‌లు లేవు",
    bookmarkedToast       = "బుక్‌మార్క్‌లలో భద్రపరచబడింది",
    removedBookmarkToast  = "బుక్‌మార్క్‌ల నుండి తొలగించబడింది",
    scanningDocument      = "పత్రాన్ని స్కాన్ చేస్తోంది...",
    madeWithCare          = "భారతదేశం కోసం శ్రద్ధగా తయారు చేయబడింది.",
    legalSosTitle         = "చట్టపరమైన SOS & హెల్ప్‌లైన్లు",
    myMattersTitle        = "నా కేసులు",
    searchMattersHint     = "కేసులు, విభాగాలు, రాష్ట్రాలను వెతకండి...",
    whatHappenedAction    = "ఏమి జరిగింది?",
    startCaseIntake       = "కేసు వివరాలు నమోదు చేయండి",
    noMattersYet          = "ఇంకా ఎలాంటి కేసులు లేవు",
    noMattersDesc         = "చట్టపరమైన కార్యాచరణ ప్రణాళికను పొందడానికి ఏమి జరిగిందో వివరించండి.",
    syncedBadge           = "సింక్ చేయబడింది",
    deleteMatterAction    = "కేసు తొలగించండి",
    tabOverview           = "అవలోకనం",
    tabTimeline           = "కాలక్రమం",
    tabActionPlan         = "కార్యాచరణ ప్రణాళిక",
    tabEvidence           = "సాక్ష్యాలు",
    tabCitations          = "చట్ట నిబంధనలు",
    tabQuestions          = "ప్రశ్నలు",
    badgeSeniorAdvocate   = "⚖️ సీనియర్ న్యాయవాది విధానపరమైన రూపకల్పన",
    badgeVerifiedIndianLaw = "🏛️ ధృవీకరించబడిన భారతీయ చట్టంపై ఆధారపడింది",
    badgeCodifiedExcerpts = "📖 సంహిత చట్ట సారాంశాలు",
    badgeVerifiedStatutes = "✓ ధృవీకరించబడిన శాసనాలపై ఆధారపడింది",
    badgeStatutoryGuide   = "⚡ చట్టబద్ధమైన సూచన మార్గదర్శిని",
    badgePreliminaryGuidance = "ℹ️ ప్రాథమిక చట్టపరమైన మార్గదర్శకత్వం",
)

// ── Tamil (தமிழ்) ─────────────────────────────────────────────────────────────
val tamilStrings = AppStrings(
    whatCanIHelpWith      = "நான் எவ்வாறு உதவ முடியும்?",
    scanDocument          = "ஆவணத்தை ஸ்கேன் செய்யுங்கள்",
    knowYourFIR           = "உங்கள் FIR தெரிந்துகொள்ளுங்கள்",
    draftRentAgreement    = "வாடகை ஒப்பந்தம் வரைவு",
    consumerRightsOverview = "நுகர்வோர் உரிமைகள் கண்ணோட்டம்",
    chatInputHint         = "நான் எவ்வாறு உதவ முடியும்?",
    welcomeTo             = "வரவேற்கிறோம்",
    tagline               = "உங்கள் உரிமைகளை அறியுங்கள்",
    navChat               = "அரட்டை",
    navAbout              = "பற்றி",
    navSettings           = "அமைப்புகள்",
    chatHistory           = "அரட்டை வரலாறு",
    settingsTitle         = "அமைப்புகள்",
    sectionAppearance     = "தோற்றம்",
    theme                 = "தீம்",
    themeLight            = "☀ வெளிர்",
    themeSystem           = "✓ கணினி",
    themeDark             = "🌙 இருண்ட",
    sectionPreferences    = "விருப்பங்கள்",
    notifications         = "அறிவிப்புகள்",
    notificationsSubtitle = "விழிப்பூட்டல்கள் மற்றும் புதுப்பிப்புகளை நிர்வகிக்கவும்",
    appLanguage           = "ஆப் மொழி",
    lowBandwidthMode      = "குறைந்த அலைவரிசை பயன்முறை",
    lowBandwidthSubtitle  = "2G/மெதுவான நெட்வொர்க்கில் தரவு சேமிக்க AI பதில்களை சுருக்குகிறது.",
    aiResponseLanguage    = "AI பதில் மொழி",
    aiResponseLangValue   = "ஹிங்லிஷ் (Gen-Z)",
    sectionPrivacy        = "தனியுரிமை மற்றும் தரவு",
    clearChatHistory      = "அரட்டை வரலாற்றை அழிக்கவும்",
    clearChatSubtitle     = "இந்த சாதனத்திலிருந்து அனைத்து உரையாடல்களையும் நீக்கவும்",
    privacyPolicy         = "தனியுரிமைக் கொள்கை",
    logOut                = "வெளியேறு",
    logOutSubtitle        = "உங்கள் கணக்கிலிருந்து வெளியேறுங்கள்",
    langModalTitle        = "ஆப் மொழி",
    disclaimerTitle       = "மறுப்பு",
    disclaimerBody        = "ந்யாயி கல்வி நோக்கங்களுக்காக மட்டுமே AI-உருவாக்கிய சட்ட தகவல்களை வழங்குகிறது.",
    disclaimerBullet1     = "• இந்த ஆப் தொழில்முறை சட்ட ஆலோசனைக்கு மாற்றாக இல்லை.",
    disclaimerBullet2     = "• வழங்கப்பட்ட தகவல் முழுமையாக அல்லது புதுப்பிக்கப்பட்டதாக இல்லாமல் இருக்கலாம்.",
    disclaimerBullet3     = "• தீவிர சட்ட விஷயங்களுக்கு எப்போதும் தகுதியான வழக்கறிஞரை அணுகுங்கள்.",
    iUnderstand           = "புரிந்தது",
    aboutTitle            = "பற்றி",
    aboutSubtitle         = "ஆப்பின் பின்னணி கதையை கண்டறியுங்கள்.",
    visionTitle           = "ந்யாயி பின்னால் உள்ள தொலைநோக்கு",
    visionPara1           = "இந்தியாவில், சட்டங்கள் பெரும்பாலும் சிக்கலானதாக இருப்பதாலும், சட்ட ஆலோசனை அணுகமுடியாத அளவுக்கு விலையுயர்ந்ததாக இருப்பதாலும் எண்ணற்ற குடிமக்கள் தங்கள் அடிப்படை உரிமைகளை அறியாமல் இருக்கிறார்கள்.",
    visionPara2           = "சட்டத்தை ஜனநாயகப்படுத்துவதன் மூலம் இந்த முக்கியமான இடைவெளியை நிரப்ப ந்யாயி வடிவமைக்கப்பட்டது. AI பயன்படுத்தி சிக்கலான சட்டங்களை எளிய, அன்றாட மொழியில் மொழிபெயர்ப்பதன் மூலம், ந்யாயி தனிநபர்கள் தங்கள் உரிமைகளை புரிந்துகொண்டு தகவலறிந்த முடிவுகளை எடுக்க உதவுகிறது.",
    visionPara3           = "நாங்கள் அனைவரையும்—குறிப்பாக கிராமப்புற அல்லது பின்தங்கிய சமூகங்களில் உள்ளவர்களை—ஆதரிக்க முயல்கிறோம், சட்ட விழிப்புணர்வின் சக்தியை நேரடியாக மக்களின் கைகளில் வைப்பதன் மூலம்.",
    visionPara4           = "நீதி அறிவோடு தொடங்குகிறது, மேலும் அந்த அறிவு அனைவருக்கும் கிடைக்கும் என்பதை உறுதிசெய்ய ந்யாயி இங்கே இருக்கிறது.",
    bookmarksTitle        = "சேமிக்கப்பட்ட புக்மார்க்குகள்",
    noBookmarksYet        = "இதுவரை சேமிக்கப்பட்ட புக்மார்க்குகள் இல்லை",
    bookmarkedToast       = "புக்மார்க்குகளில் சேமிக்கப்பட்டது",
    removedBookmarkToast  = "புக்மார்க்குகளிலிருந்து நீக்கப்பட்டது",
    scanningDocument      = "ஆவணம் ஸ்கேன் செய்யப்படுகிறது...",
    madeWithCare          = "இந்தியாவிற்காக அக்கறையுடன் உருவாக்கப்பட்டது.",
    legalSosTitle         = "சட்ட SOS & உதவி எண்கள்",
    myMattersTitle        = "எனது வழக்குகள்",
    searchMattersHint     = "வழக்குகள், துறைகள், மாநிலங்களைத் தேடுங்கள்...",
    whatHappenedAction    = "என்ன நடந்தது?",
    startCaseIntake       = "வழக்கு பதிவைத் தொடங்குங்கள்",
    noMattersYet          = "இதுவரை வழக்குகள் இல்லை",
    noMattersDesc         = "சட்டபூர்வ செயல் திட்டத்தைப் பெற என்ன நடந்தது என்பதை விவரிக்கவும்.",
    syncedBadge           = "ஒத்திசைக்கப்பட்டது",
    deleteMatterAction    = "வழக்கை நீக்குக",
    tabOverview           = "கண்ணோட்டம்",
    tabTimeline           = "காலக்கோடு",
    tabActionPlan         = "செயல் திட்டம்",
    tabEvidence           = "ஆதாரங்கள்",
    tabCitations          = "சட்டப் பிரிவுகள்",
    tabQuestions          = "கேள்விகள்",
    badgeSeniorAdvocate   = "⚖️ மூத்த வழக்கறிஞர் நடைமுறை கட்டமைப்பு",
    badgeVerifiedIndianLaw = "🏛️ சரிபார்க்கப்பட்ட இந்திய சட்டத்தின் அடிப்படை",
    badgeCodifiedExcerpts = "📖 தொகுக்கப்பட்ட சட்டக் குறிப்புகள்",
    badgeVerifiedStatutes = "✓ சரிபார்க்கப்பட்ட சட்டங்களின் அடிப்படை",
    badgeStatutoryGuide   = "⚡ சட்டப்பூர்வ குறிப்பு வழிகாட்டி",
    badgePreliminaryGuidance = "ℹ️ முதற்கட்ட சட்ட வழிகாட்டுதல்",
)

// ── Factory ───────────────────────────────────────────────────────────────────
fun stringsFor(lang: AppLanguage): AppStrings = when (lang) {
    AppLanguage.ENGLISH -> englishStrings
    AppLanguage.HINDI   -> hindiStrings
    AppLanguage.BENGALI -> bengaliStrings
    AppLanguage.TELUGU  -> teluguStrings
    AppLanguage.TAMIL   -> tamilStrings
}
